# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faceWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_faceWidget(object):
    def setupUi(self, faceWidget):
        faceWidget.setObjectName("faceWidget")
        faceWidget.resize(1200, 840)
        faceWidget.setMinimumSize(QtCore.QSize(1000, 630))
        faceWidget.setMaximumSize(QtCore.QSize(9999999, 9999999))
        faceWidget.setStyleSheet("#faceWidget{\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
".QWidget{\n"
"    border-radius: 8px;\n"
"}\n"
"#graphicArea{\n"
"    background-color: rgb(210, 210, 210);\n"
"    border-radius: 8px;\n"
"}\n"
"#handleCalcBtn{\n"
"    image:url(./resource/images/btn.png);\n"
"}\n"
"#handleCalcBtn:hover{\n"
"    image:url(./resource/images/btn_hover.png);\n"
"}\n"
"#handleCalcBtn:pressed{\n"
"    image:url(./resource/images/btn_pressed.png);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(faceWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tool_area = QtWidgets.QWidget(faceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_area.sizePolicy().hasHeightForWidth())
        self.tool_area.setSizePolicy(sizePolicy)
        self.tool_area.setMinimumSize(QtCore.QSize(0, 60))
        self.tool_area.setStyleSheet("#tool_area{\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"")
        self.tool_area.setObjectName("tool_area")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tool_area)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(5, 0, 11, -1)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.handleCalcBtn = QtWidgets.QPushButton(self.tool_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.handleCalcBtn.sizePolicy().hasHeightForWidth())
        self.handleCalcBtn.setSizePolicy(sizePolicy)
        self.handleCalcBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.handleCalcBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.handleCalcBtn.setWhatsThis("")
        self.handleCalcBtn.setStyleSheet("border-style:none")
        self.handleCalcBtn.setInputMethodHints(QtCore.Qt.ImhNone)
        self.handleCalcBtn.setText("")
        self.handleCalcBtn.setObjectName("handleCalcBtn")
        self.horizontalLayout_6.addWidget(self.handleCalcBtn)
        spacerItem = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.tool_area)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.up_Shift = QtWidgets.QSpinBox(self.tool_area)
        self.up_Shift.setMinimumSize(QtCore.QSize(100, 0))
        self.up_Shift.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.up_Shift.setMaximum(999)
        self.up_Shift.setProperty("value", 15)
        self.up_Shift.setObjectName("up_Shift")
        self.horizontalLayout_6.addWidget(self.up_Shift)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.tool_area)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.low_Shift = QtWidgets.QSpinBox(self.tool_area)
        self.low_Shift.setMinimumSize(QtCore.QSize(100, 0))
        self.low_Shift.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.low_Shift.setMaximum(999)
        self.low_Shift.setProperty("value", 15)
        self.low_Shift.setObjectName("low_Shift")
        self.horizontalLayout_6.addWidget(self.low_Shift)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_6.setStretch(0, 4)
        self.horizontalLayout_6.setStretch(7, 50)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.tool_area, 1, 1, 1, 2)
        self.graphicArea = QtWidgets.QWidget(faceWidget)
        self.graphicArea.setStyleSheet("")
        self.graphicArea.setObjectName("graphicArea")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.graphicArea)
        self.gridLayout_4.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicStack = QtWidgets.QStackedWidget(self.graphicArea)
        self.graphicStack.setStyleSheet("#graphicStack{\n"
"    border-style: none;\n"
"}")
        self.graphicStack.setObjectName("graphicStack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.graphicStack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.graphicStack.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.graphicStack, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.graphicArea, 0, 0, 1, 3)
        self.file_area = QtWidgets.QWidget(faceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_area.sizePolicy().hasHeightForWidth())
        self.file_area.setSizePolicy(sizePolicy)
        self.file_area.setMinimumSize(QtCore.QSize(302, 0))
        self.file_area.setStyleSheet("QWidget#file_area{\n"
"    background-color: rgb(245,245,245);\n"
"}")
        self.file_area.setObjectName("file_area")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.file_area)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fileTableWidget = QtWidgets.QTableWidget(self.file_area)
        self.fileTableWidget.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-style: none")
        self.fileTableWidget.setLineWidth(1)
        self.fileTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fileTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileTableWidget.setRowCount(20)
        self.fileTableWidget.setColumnCount(1)
        self.fileTableWidget.setObjectName("fileTableWidget")
        self.gridLayout_2.addWidget(self.fileTableWidget, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.file_area, 1, 0, 2, 1)
        self.dataArea = QtWidgets.QWidget(faceWidget)
        self.dataArea.setMinimumSize(QtCore.QSize(0, 250))
        self.dataArea.setMaximumSize(QtCore.QSize(99999, 250))
        self.dataArea.setStyleSheet("\n"
"")
        self.dataArea.setObjectName("dataArea")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dataArea)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dataStack = QtWidgets.QStackedWidget(self.dataArea)
        self.dataStack.setStyleSheet("#dataStack{\n"
"    background-color: rgb(245,245,245);\n"
"}\n"
"")
        self.dataStack.setObjectName("dataStack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.dataStack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.dataStack.addWidget(self.page_4)
        self.gridLayout_5.addWidget(self.dataStack, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.dataArea, 2, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 310)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(faceWidget)
        self.graphicStack.setCurrentIndex(1)
        self.dataStack.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(faceWidget)
        faceWidget.setTabOrder(self.up_Shift, self.low_Shift)
        faceWidget.setTabOrder(self.low_Shift, self.handleCalcBtn)
        faceWidget.setTabOrder(self.handleCalcBtn, self.fileTableWidget)

    def retranslateUi(self, faceWidget):
        _translate = QtCore.QCoreApplication.translate
        faceWidget.setWindowTitle(_translate("faceWidget", "Form"))
        self.handleCalcBtn.setToolTip(_translate("faceWidget", "开始计算"))
        self.label.setText(_translate("faceWidget", "上限偏移量"))
        self.label_2.setText(_translate("faceWidget", "下限偏移量"))
